name: audioplayers_android
description: Android implementation of audioplayers, a Flutter plugin to play multiple audio files simultaneously
version: 0.20.1
homepage: https://github.com/luanpotter/audioplayers

flutter:
  plugin:
    platforms:
      android:
        package: xyz.luan.audioplayers
        pluginClass: AudioplayersPlugin

dependencies:
  audioplayers_platform_interface:
    path: ../audioplayers_platform_interface
  uuid: ^3.0.1
  path_provider: ^2.0.1
  http: ^0.13.1
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flame_lint: 0.0.1
  dartdoc: ^2.0.0

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.10.0"

