name: audioplayers_platform_interface
description: The platform interface for audioplayers, a Flutter plugin to play multiple audio files simultaneously
version: 0.20.1
homepage: https://github.com/luanpotter/audioplayers

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flame_lint: 0.0.1
  dartdoc: ^2.0.0

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.10.0"